'use strict';

const OPCODES = {
  CONTINUATION: 0x00,
  TEXT: 0x01,
  BINARY: 0x02,
  CLOSE: 0x08,
  PING: 0x09,
  PONG: 0x0a,
};

const CLOSE_CODES = {
  NORMAL_CLOSE: 1000,
  GOING_AWAY: 1001,
  PROTOCOL_ERROR: 1002,
  UNSUPPORTED_DATA: 1003,
  RESERVED: 1004,
  NO_CODE_RECEIVED: 1005,
  CONNECTION_CLOSED_ABNORMALLY: 1006,
  INVALID_PAYLOAD: 1007,
  POLICY_VIOLATED: 1008,
  MESSAGE_TOO_BIG: 1009,
  MANDATORY_EXTENSION: 1010,
  INTERNAL_SERVER_ERROR: 1011,
  TLS_HANDSHAKE: 1015,
};

const DATA_OPCODES = new Set([
  OPCODES.CONTINUATION,
  OPCODES.TEXT,
  OPCODES.BINARY,
]);

const CONTROL_OPCODES = new Set([OPCODES.CLOSE, OPCODES.PING, OPCODES.PONG]);

module.exports = { OPCODES, CLOSE_CODES, DATA_OPCODES, CONTROL_OPCODES };
